export const OurWorksData = [
    {
        s_no: 1,
        Category: "Cafe",
        SiteName: "chennaicafe",
        description: "Chennai Cafe - A place for authentic Chennai cuisine.",
        imageaddress: "/assets/images/demo/Ourworksimg1.png",
        screenShotaddress: "/assets/images/demo/catering.png",
        WebsiteLink: "https://chennaicafe.shop/",
        siteId: "chennaicafe_shop_123abc456def789ghi",
        headText: "Explore Chennai Cuisine",
        headDescription: "Discover authentic Chennai cuisine at Chennai Cafe."
    },
    {
        s_no: 2,
        Category: "Travels",
        SiteName: "axesstravels",
        description: "Axes Travels - Your gateway to seamless travel experiences.",
        imageaddress: "/assets/images/demo/Ourworksimg2.png",
        screenShotaddress: "/assets/images/demo/gift.png",
        WebsiteLink: "https://axesstravels.in/",
        siteId: "axesstravels_in_456def789ghi123abc",
        headText: "Seamless Travel Experiences",
        headDescription: "Explore seamless travel experiences with Axes Travels."
    },
    {
        s_no: 3,
        Category: "E-Commerce",
        SiteName: "VividWear",
        description: "Vivid Wear - Fashion that defines your style.",
        imageaddress: "/assets/images/demo/Ourworksimg3.png",
        screenShotaddress: "/assets/images/demo/photography.png",
        WebsiteLink: "https://vividwear.live/",
        siteId: "vividwear_live_789ghi123abc456def",
        headText: "Define Your Style",
        headDescription: "Discover fashion that defines your unique style at Vivid Wear."
    },
    {
        s_no: 4,
        Category: "School",
        SiteName: "LearnFast",
        description: "LearnFast - Accelerate your learning journey.",
        imageaddress: "/assets/images/demo/Ourworksimg1.png",
        screenShotaddress: "/assets/images/demo/porfolio2.png",
        WebsiteLink: "https://learnfast.live/",
        siteId: "learnfast_live_123abc456def789ghi",
        headText: "Accelerate Your Learning",
        headDescription: "Accelerate your learning journey with LearnFast."
    },
    {
        s_no: 5,
        Category: "Restaurant",
        SiteName: "FlavorFusion",
        description: "Flavor Fusion - Where taste meets innovation.",
        imageaddress: "/assets/images/demo/Ourworksimg2.png",
        screenShotaddress: "/assets/images/demo/porfolio1.png",
        WebsiteLink: "https://flavorfusion.live/",
        siteId: "flavorfusion_live_456def789ghi123abc",
        headText: "Taste Meets Innovation",
        headDescription: "Experience where taste meets innovation at Flavor Fusion."
    },
    {
        s_no: 6,
        Category: "Hospital",
        SiteName: "Unity Health Center",
        description: "Unity Health Center - Comprehensive healthcare services.",
        imageaddress: "/assets/images/demo/Ourworksimg3.png",
        screenShotaddress: "/assets/images/demo/catering.png",
        screenShotaddress: "/assets/images/demo/watch.png",
        WebsiteLink: "https://unityhealthcenter.live/",
        siteId: "unityhealthcenter_live_789ghi123abc456def",
        headText: "Comprehensive Healthcare",
        headDescription: "Providing comprehensive healthcare services at Unity Health Center."
    },
    {
        s_no: 7,
        Category: "Portfolio",
        SiteName: "morgan john",
        description: "Morgan John - Showcasing creative portfolios.",
        imageaddress: "/assets/images/demo/Ourworksimg1.png",
        screenShotaddress: "/assets/images/demo/catering.png",
        WebsiteLink: "https://morganjohn.pro/",
        siteId: "morganjohn_pro_123abc456def789ghi",
        headText: "Showcase Your Creativity",
        headDescription: "Showcase your creative portfolios with Morgan John."
    },
    {
        s_no: 8,
        Category: "RealEstate",
        SiteName: "Elite Estates",
        description: "Elite Estates - Your partner in real estate investments.",
        imageaddress: "/assets/images/demo/Ourworksimg2.png",
        screenShotaddress: "/assets/images/demo/gift.png",
        WebsiteLink: "http://eliteestates.site/",
        siteId: "eliteestates_site_456def789ghi123abc",
        headText: "Real Estate Investments",
        headDescription: "Your partner in real estate investments at Elite Estates."
    },
    {
        s_no: 9,
        Category: "Gym",
        SiteName: "Body Temple",
        description: "Body Temple - Fitness redefined for a healthier you.",
        imageaddress: "/assets/images/demo/Ourworksimg3.png",
        screenShotaddress: "/assets/images/demo/photography.png",
        WebsiteLink: "https://bodytemple.pro/",
        siteId: "bodytemple_pro_789ghi123abc456def",
        headText: "Fitness Redefined",
        headDescription: "Redefined fitness for a healthier you at Body Temple."
    },
    {
        s_no: 10,
        Category: "Gaming",
        SiteName: "Dream Game Builders",
        description: "Dream Game Builders - Crafting your gaming dreams.",
        imageaddress: "/assets/images/demo/Ourworksimg1.png",
        screenShotaddress: "/assets/images/demo/porfolio2.png",
        WebsiteLink: "https://dreamgamebuilders.pro/",
        siteId: "dreamgamebuilders_pro_123abc456def789ghi",
        headText: "Craft Your Gaming Dreams",
        headDescription: "Crafting your gaming dreams with Dream Game Builders."
    },
    {
        s_no: 11,
        Category: "Education",
        SiteName: "LearnFlex Online",
        description: "LearnFlex Online - Flexible learning solutions for all.",
        imageaddress: "/assets/images/demo/Ourworksimg2.png",
        screenShotaddress: "/assets/images/demo/porfolio1.png",
        WebsiteLink: "https://learnflex.online/",
        siteId: "learnflex_online_456def789ghi123abc",
        headText: "Flexible Learning Solutions",
        headDescription: "Explore flexible learning solutions for all at LearnFlex Online."
    },
    {
        s_no: 12,
        Category: "Insurance",
        SiteName: "Trust Guard",
        description: "Trust Guard Insurance - Your trusted insurance partner.",
        imageaddress: "/assets/images/demo/Ourworksimg3.png",
        screenShotaddress: "/assets/images/demo/watch.png",
        WebsiteLink: "https://trustguardinsurance.in/",
        siteId: "trustguardinsurance_in_789ghi123abc456def",
        headText: "Your Trusted Insurance Partner",
        headDescription: "Trust Guard Insurance - Providing insurance solutions you can trust."
    },
    {
        s_no: 13,
        Category: "Rental Cars",
        SiteName: "Velocity Car Rentals",
        description: "Velocity Car Rentals - Drive your way with ease.",
        imageaddress: "/assets/images/demo/Ourworksimg1.png",
        screenShotaddress: "/assets/images/demo/catering.png",
        WebsiteLink: "https://velocitycarrentals.live/",
        siteId: "velocitycarrentals_live_123abc456def789ghi",
        headText: "Drive with Ease",
        headDescription: "Drive your way with ease with Velocity Car Rentals."
    },
    {
        s_no: 14,
        Category: "Bakery",
        SiteName: "Delightful Desserts",
        description: "Delightful Desserts - Sweet treats for every occasion.",
        imageaddress: "/assets/images/demo/Ourworksimg2.png",
        screenShotaddress: "/assets/images/demo/gift.png",
        WebsiteLink: "https://delightfuldesserts.shop/",
        siteId: "delightfuldesserts_shop_456def789ghi123abc",
        headText: "Sweet Treats for Every Occasion",
        headDescription: "Enjoy sweet treats for every occasion at Delightful Desserts."
    },
    {
        s_no: 15,
        Category: "Events",
        SiteName: "EventExcellence",
        description: "Event Excellence - Making your events extraordinary.",
        imageaddress: "/assets/images/demo/Ourworksimg3.png",
        screenShotaddress: "/assets/images/demo/photography.png",
        WebsiteLink: "https://eventexcellence.pro/",
        siteId: "eventexcellence_pro_789ghi123abc456def",
        headText: "Extraordinary Events",
        headDescription: "Make your events extraordinary with Event Excellence."
    }
];
